name: Show Platform Paths
on:
  workflow_dispatch:

jobs:
  show-paths:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Deno
        uses: denoland/setup-deno@v2

      - name: Show platform directories
        run: deno task result
